In [1]:
import numpy as np
import pandas as pd
import requests

In [2]:
url = "https://raw.githubusercontent.com/Data-for-Palestine/Palestinian-Movies-JSON-Dataset/main/palestinian_movies.json"

In [3]:
req = requests.get(url)

In [4]:
req.json()

{'movies': [{'titleText': {'text': 'Curfew'},
   'id': 'tt0109996',
   'primaryImage': {'id': 'rm777481472',
    'width': 315,
    'height': 420,
    'url': 'https://m.media-amazon.com/images/M/MV5BZWJhODQ3NWQtMDk1YS00Y2FlLWE0ZDMtNTlhODUxMzI0MWI3XkEyXkFqcGdeQXVyNzQwMzAwNTI@._V1_.jpg',
    'caption': {'plainText': 'Curfew (1994)'}},
   'releaseDate': {'day': 5,
    'month': 12,
    'year': 1994,
    'country': {'id': 'US', 'text': 'United States'}},
   'plot': {'plotText': {'plainText': '24 hours of family drama during a curfew announced by the Israeli army in a Palestinian refugee camp on the Gaza Strip in 1993.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Hikayatul jawahiri thalath'},
   'id': 'tt0111354',
   'primaryImage': {'id': 'rm4037123328',
    'width': 284,
    'height': 475,
    'url': 'https://m.media-amazon.com/images/M/MV5BMTk5MTk2Njk5NF5BMl5BanBnXkFtZTcwODk4OTUyMQ@@._V1_.jpg',
    'caption': {'plainText': 'Hikayatul jawahiri thalath (1995)'}},
   'releaseDate': {'day': 6,
    'month': 12,
    'year': 1995,
    'country': {'id': 'FR', 'text': 'France'}},
   'plot': {'plotText': {'plainText': "A Palestinian boy becomes entranced with a beautiful Gypsy girl and a fairy tale world she weaves amidst conflict in Gaza. The children explore nature, mysticism and what their future holds, while learning to live with the surrounding brutality c. 1990. Yusef's family scrapes by in a seaside camp while his father's in prison and his heavily-armed brother's on the run, parrying with Israeli troops. Salah, Yusef's schoolmate from a well-off Arab family strives faithfully to assist them, while Yusef helps an elderly, blind neighbor escape from his lonely abandonment into the North American dreamworld he's waited so long for."},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Giraffada'},
   'id': 'tt3132086',
   'primaryImage': {'id': 'rm2021999616',
    'width': 950,
    'height': 1344,
    'url': 'https://m.media-amazon.com/images/M/MV5BNDRiNjI5YjgtNTFkZi00Y2I4LThhYzktOTgxY2QxYmM3NjdiXkEyXkFqcGdeQXVyMzA3Njg4MzY@._V1_.jpg',
    'caption': {'plainText': 'Ahmad Bayatra in Giraffada (2013)'}},
   'releaseDate': {'day': 23,
    'month': 4,
    'year': 2014,
    'country': {'id': 'FR', 'text': 'France'}},
   'plot': {'plotText': {'plainText': 'A male giraffe dies after a nocturnal air raid in a Palestinian zoo. The female giraffe stops eating. A boy and his father, the veterinarian of the zoo, look for a solution.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Gaza mon amour'},
   'id': 'tt11692148',
   'primaryImage': {'id': 'rm2123225857',
    'width': 1080,
    'height': 1617,
    'url': 'https://m.media-amazon.com/images/M/MV5BOGViNDMyZDYtMWFkNS00YmE4LThkZjYtMTg3ZTA0ZTE3ZWNlXkEyXkFqcGdeQXVyNTM2NTg3Nzg@._V1_.jpg',
    'caption': {'plainText': 'Gaza mon amour (2020)'}},
   'releaseDate': {'day': 5,
    'month': 11,
    'year': 2021,
    'country': {'id': 'US', 'text': 'United States'}},
   'plot': {'plotText': {'plainText': 'Gaza, today. Sixty-year-old fisherman Issa is secretly in love with Siham, a woman who works at the market with her daughter Leila. When he discovers an ancient phallic statue of Apollo in his fishing nets, Issa hides it, not knowing what to do with this mysterious and potent treasure. Yet deep inside, he feels that this discovery will change his life forever. Strangely, his confidence starts to grow and eventually he decides to approach Siham.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Farha'},
   'id': 'tt11555492',
   'primaryImage': {'id': 'rm2816411393',
    'width': 4000,
    'height': 5684,
    'url': 'https://m.media-amazon.com/images/M/MV5BM2NiMDBkMTYtY2E5NC00Y2EwLTlmNzUtOTFjZDM0NTRkOTA5XkEyXkFqcGdeQXVyODM1Mjc5MjU@._V1_.jpg',
    'caption': {'plainText': 'Karam Taher and Ashraf Barhom in Farha (2021)'}},
   'releaseDate': {'day': 1,
    'month': 12,
    'year': 2022,
    'country': {'id': 'US', 'text': 'United States'}},
   'plot': {'plotText': {'plainText': 'A 14-year-old girl in 1948 Palestine watches from a locked pantry as catastrophe consumes her home.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Eyes of a Thief'},
   'id': 'tt2993406',
   'primaryImage': {'id': 'rm22085376',
    'width': 814,
    'height': 1137,
    'url': 'https://m.media-amazon.com/images/M/MV5BNDIwODE3MjcwOV5BMl5BanBnXkFtZTgwNTYxMjU5MzE@._V1_.jpg',
    'caption': {'plainText': 'Eyes of a Thief (2014)'}},
   'releaseDate': {'day': 1,
    'month': 10,
    'year': 2014,
    'country': {'id': 'PS', 'text': 'Occupied Palestinian Territory'}},
   'plot': {'plotText': {'plainText': 'A father with a dangerous secret searches for his daughter.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Habibi Rasak Kharban'},
   'id': 'tt1670646',
   'primaryImage': {'id': 'rm1752743424',
    'width': 3995,
    'height': 2249,
    'url': 'https://m.media-amazon.com/images/M/MV5BMTk1NzE4NDc3Ml5BMl5BanBnXkFtZTcwMDIxODQ2NQ@@._V1_.jpg',
    'caption': {'plainText': 'Kais Nashif and Maisa Abd Elhadi in Habibi Rasak Kharban (2011)'}},
   'releaseDate': {'day': 15,
    'month': 5,
    'year': 2012,
    'country': {'id': 'PS', 'text': 'Occupied Palestinian Territory'}},
   'plot': {'plotText': {'plainText': "'Habibi Rasak Kharban' (Darling, Something's Wrong with Your Head) is a dramatic feature that tells the story of a forbidden love in Gaza. The film is a modern re-telling of the famous ancient Sufi parable 'Majnun Layla'."},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Falastine Stereo'},
   'id': 'tt3121066',
   'primaryImage': {'id': 'rm2102016000',
    'width': 630,
    'height': 893,
    'url': 'https://m.media-amazon.com/images/M/MV5BNmZiNDA4NjYtY2Y5Ny00MjdiLTg1ZjYtMTIyZDI5OGI3MTYwL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQ3Njg3MQ@@._V1_.jpg',
    'caption': {'plainText': 'Falastine Stereo (2013)'}},
   'releaseDate': {'day': 2,
    'month': 6,
    'year': 2014,
    'country': {'id': 'US', 'text': 'United States'}},
   'plot': {'plotText': {'plainText': "Two Palestinian brothers plan on immigrating to Canada after the Israeli air force bombs their family home. Milad (Stereo) used to be a wedding singer but because his wife dies in the attack he doesn't want to live in palestine or sing anymore. The bombing also leaves his brother Samy mute and deaf. The two set about earning money for their travel to Canada by buying a secondhand sound system that they rent out for events in Ramallah."},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Chronicle of a Disappearance'},
   'id': 'tt0115895',
   'primaryImage': {'id': 'rm2871237888',
    'width': 344,
    'height': 500,
    'url': 'https://m.media-amazon.com/images/M/MV5BMTc3ODMwMzg1NV5BMl5BanBnXkFtZTcwNjg3NjAzMQ@@._V1_.jpg',
    'caption': {'plainText': 'Chronicle of a Disappearance (1996)'}},
   'releaseDate': {'day': None,
    'month': None,
    'year': 1996,
    'country': {'id': 'IL', 'text': 'Israel'}},
   'plot': {'plotText': {'plainText': "A Palestinian expatriate filmmaker (Elia Suleiman) documents the loss of national identity in Israel's Arab population."},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': "Laila's Birthday"},
   'id': 'tt1281951',
   'primaryImage': {'id': 'rm3684775681',
    'width': 560,
    'height': 800,
    'url': 'https://m.media-amazon.com/images/M/MV5BMjhmOTZjMTMtMDQ4ZS00NDcwLTkxNzctYmE2MmQzOThjMDQ1XkEyXkFqcGdeQXVyMTQ4OTk3MzM@._V1_.jpg',
    'caption': {'plainText': "Laila's Birthday (2008)"}},
   'releaseDate': {'day': 9,
    'month': 4,
    'year': 2009,
    'country': {'id': 'NL', 'text': 'Netherlands'}},
   'plot': {'plotText': {'plainText': "Abu Laila used to be a judge, but because the government doesn't have the means to renew his assignment he is forced to be a taxi driver. On the day his daughter Laila becomes seven years old his wife insists that he'll be at home early and bring her a present and a cake. Abu Laila's has nothing else on his mind then completing this mission. But the daily life in Palestine has other plans."},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Lemon Tree'},
   'id': 'tt1172963',
   'primaryImage': {'id': 'rm3732179712',
    'width': 260,
    'height': 382,
    'url': 'https://m.media-amazon.com/images/M/MV5BMTg5NTM0OTE3OV5BMl5BanBnXkFtZTcwMjk4ODM0Mg@@._V1_.jpg',
    'caption': {'plainText': 'Lemon Tree (2008)'}},
   'releaseDate': {'day': 27,
    'month': 3,
    'year': 2008,
    'country': {'id': 'IL', 'text': 'Israel'}},
   'plot': {'plotText': {'plainText': 'The story of a Palestinian widow who must defend her lemontree field when a new Israeli Defense Minister moves next to her and threatens to have her lemon grove torn down.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Degrade'},
   'id': 'tt4429074',
   'primaryImage': {'id': 'rm1215045120',
    'width': 736,
    'height': 981,
    'url': 'https://m.media-amazon.com/images/M/MV5BOTg3ZDJlMTctZjc3MS00Y2MyLThmYWUtNjEwZTE4YzQ0YWQ4XkEyXkFqcGdeQXVyMjY4OTU1NTE@._V1_.jpg',
    'caption': {'plainText': 'Degrade (2015)'}},
   'releaseDate': {'day': 27,
    'month': 4,
    'year': 2016,
    'country': {'id': 'FR', 'text': 'France'}},
   'plot': {'plotText': {'plainText': 'In Gaza, two hairdressers and ten customers of various ages and backgrounds spend the day trapped in a beauty salon while Hamas police fight a gang in the street.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Bethlehem'},
   'id': 'tt2915160',
   'primaryImage': {'id': 'rm1833487360',
    'width': 4015,
    'height': 5787,
    'url': 'https://m.media-amazon.com/images/M/MV5BMTc5OTUwMjgyOF5BMl5BanBnXkFtZTgwNTA3NzAwMjE@._V1_.jpg',
    'caption': {'plainText': "Shadi Mar'i and Tsahi Halevi in Bethlehem (2013)"}},
   'releaseDate': {'day': 26,
    'month': 9,
    'year': 2013,
    'country': {'id': 'IL', 'text': 'Israel'}},
   'plot': {'plotText': {'plainText': 'Tells the story of the complex relationship between an Israeli Secret Service officer and his teenage Palestinian informant. Shuttling back and forth between conflicting points of view, the film is a raw portrayal of characters torn apart by competing loyalties and impossible moral dilemmas, giving an unparalleled glimpse into the dark and fascinating world of human intelligence.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Bonboné'},
   'id': 'tt7083868',
   'primaryImage': {'id': 'rm62413312',
    'width': 8100,
    'height': 12000,
    'url': 'https://m.media-amazon.com/images/M/MV5BOTQwMGYwYWMtNjIxOC00Y2RlLWFiMTgtZTM2YzgxYzhkZDZiXkEyXkFqcGdeQXVyMjUzNjAxNTM@._V1_.jpg',
    'caption': {'plainText': 'Rana Alamuddin and Saleh Bakri in Bonboné (2017)'}},
   'releaseDate': {'day': 4,
    'month': 10,
    'year': 2017,
    'country': {'id': 'US', 'text': 'United States'}},
   'plot': {'plotText': {'plainText': 'A Palestinian couple resorts to an unusual way to conceive as the husband is detained in an Israeli jail where visits are restricted.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Between Heaven and Earth'},
   'id': 'tt10111746',
   'primaryImage': {'id': 'rm232360193',
    'width': 1080,
    'height': 695,
    'url': 'https://m.media-amazon.com/images/M/MV5BMTk1ZmNjZjMtYzdiOS00YzYwLWI3ZGEtMTcyYjBiMjZjYzJmXkEyXkFqcGdeQXVyNDEzNzEzNw@@._V1_.jpg',
    'caption': {'plainText': 'Between Heaven and Earth (2019)'}},
   'releaseDate': {'day': 2,
    'month': 12,
    'year': 2020,
    'country': {'id': 'EG', 'text': 'Egypt'}},
   'plot': {'plotText': {'plainText': 'Two married young couple are going through steps to get divorced when the husband finds out secrets about his past'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'In Between'},
   'id': 'tt5974388',
   'primaryImage': {'id': 'rm3107544832',
    'width': 1611,
    'height': 2304,
    'url': 'https://m.media-amazon.com/images/M/MV5BNjIzZGM5MWQtYmUzMS00NTViLTgyNGYtODQ1ZDE5YjM1MWViXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
    'caption': {'plainText': 'Mouna Hawa, Sana Jammelieh, and Shaden Kanboura in In Between (2016)'}},
   'releaseDate': {'day': 5,
    'month': 1,
    'year': 2017,
    'country': {'id': 'IL', 'text': 'Israel'}},
   'plot': {'plotText': {'plainText': 'Three Palestinian women living in an apartment in Tel Aviv try to find a balance between traditional and modern culture.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Bab el shams'},
   'id': 'tt0406551',
   'primaryImage': {'id': 'rm3200061184',
    'width': 350,
    'height': 497,
    'url': 'https://m.media-amazon.com/images/M/MV5BOWZkZDY5YWMtOWVkNC00ZDQ2LWE5NGItY2EwODE0YTllMmNjXkEyXkFqcGdeQXVyNjg2NTg4OTY@._V1_.jpg',
    'caption': {'plainText': 'Bab el shams (2004)'}},
   'releaseDate': {'day': 19,
    'month': 1,
    'year': 2005,
    'country': {'id': 'EG', 'text': 'Egypt'}},
   'plot': {'plotText': {'plainText': "In the beginning was Palestine, and the story of Younes (Orwa Nyrabia) began, known as Abou Salem, known as the Man, said to be the father of Ibrahim, fighting the English from the age of 16, still fighting, but retrenched in the Lebanon, illegal in his own country ; the story of Nahila (Rim Turki) also began, married to him when she was twelve, breast-feeding their first child, born during the villagers' exhausting trek towards the North, fleeing their burning homes, Nahila whom he met secretly in a cave in Bab El Chams, in Galilee. Again it is the story of Doctor Khalil (Bassel Khayat), abandoned by his mother in the shambles of the refugee camps, who, in Beirut, rescued Younes in a deep coma, lulling him with the tragic story of his people ; and yet again it is that of Chams (Hala Omran) whom Khalil loved and was executed by his companions in arms. Fifty years of history full of suffering, hope and love."},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Al-mor wa al rumman'},
   'id': 'tt1320282',
   'primaryImage': {'id': 'rm850923776',
    'width': 517,
    'height': 800,
    'url': 'https://m.media-amazon.com/images/M/MV5BYTc0MmUyNTEtZWQ4MS00ZWU3LThmYjktZTE1OWUyOGJkZDgyXkEyXkFqcGdeQXVyMzExODEzNDA@._V1_.jpg',
    'caption': {'plainText': 'Al-mor wa al rumman (2008)'}},
   'releaseDate': {'day': None,
    'month': 2,
    'year': 2009,
    'country': {'id': 'DE', 'text': 'Germany'}},
   'plot': {'plotText': {'plainText': 'A free spirited Palestinian dancer becomes the wife of a prisoner.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'The Present'},
   'id': 'tt11474480',
   'primaryImage': {'id': 'rm92910337',
    'width': 2305,
    'height': 3439,
    'url': 'https://m.media-amazon.com/images/M/MV5BNTM2ZWQ3NzktNDY4MS00YzhmLWI0YTktYjUzNDljZDA0M2FmXkEyXkFqcGdeQXVyNjYxMDQwOTI@._V1_.jpg',
    'caption': {'plainText': 'The Present (2020)'}},
   'releaseDate': {'day': 18,
    'month': 3,
    'year': 2021,
    'country': {'id': 'SG', 'text': 'Singapore'}},
   'plot': {'plotText': {'plainText': 'On his wedding anniversary, Yusef and his young daughter set out in the West Bank to buy his wife a gift. Between soldiers, segregated roads and checkpoints, how easy would it be to go shopping?'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Love, Theft and Other Entanglements'},
   'id': 'tt4253322',
   'primaryImage': {'id': 'rm1309341184',
    'width': 467,
    'height': 661,
    'url': 'https://m.media-amazon.com/images/M/MV5BMjE1NDMwMzk3MV5BMl5BanBnXkFtZTgwODEzMDc0NTE@._V1_.jpg',
    'caption': {'plainText': 'Love, Theft and Other Entanglements (2015)'}},
   'releaseDate': {'day': 26,
    'month': 5,
    'year': 2016,
    'country': {'id': 'PS', 'text': 'Occupied Palestinian Territory'}},
   'plot': {'plotText': {'plainText': 'A Palestinian car thief gets into the trouble of his life when he steals the wrong car. What he thought was an Israeli car and an easy way to make money in his impoverished refugee camp turns out to be a load of misfortune when he discovers a kidnapped Israeli soldier in the trunk.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Al-Nakba'},
   'id': 'tt3850118',
   'primaryImage': {'id': 'rm261240833',
    'width': 1114,
    'height': 1486,
    'url': 'https://m.media-amazon.com/images/M/MV5BMDM4YWE0NDgtZmNjNC00MzRiLWFmOWMtZWFmY2Y3ZTBkMTA1XkEyXkFqcGdeQXVyMTUyMjEyMjMx._V1_.jpg',
    'caption': {'plainText': 'Al-Nakba (2008)'}},
   'releaseDate': {'day': None,
    'month': None,
    'year': 2008,
    'country': {'id': 'QA', 'text': 'Qatar'}},
   'plot': {'plotText': {'plainText': 'The ethnic cleansing that occurred during the creation of the State of Israel is known to Palestinians as Nakba, which means "catastrophe."'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': '1948 Palestinian Exodus'},
   'id': 'tt0163518',
   'primaryImage': {'id': 'rm2382833664',
    'width': 229,
    'height': 316,
    'url': 'https://m.media-amazon.com/images/M/MV5BYjJiZWM1MGMtNzkyZS00ZGU4LWE1NDctMzI0YWQ3MDVkN2UwXkEyXkFqcGdeQXVyMjMyMzI4MzY@._V1_.jpg',
    'caption': {'plainText': '1948 Palestinian Exodus (1997)'}},
   'releaseDate': {'day': None,
    'month': None,
    'year': 1997,
    'country': {'id': 'IL', 'text': 'Israel'}},
   'plot': {'plotText': {'plainText': 'The film presents eyewitness accounts of Palestinian refugees and Zionist soldiers to tell the story of the displacement of 750,000 Palestinians as a part of the creation of the state of Israel.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'The Sons of Eilaboun'},
   'id': 'tt1249418',
   'primaryImage': {'id': 'rm1201834496',
    'width': 300,
    'height': 427,
    'url': 'https://m.media-amazon.com/images/M/MV5BMTYxNjU2MzQ4Ml5BMl5BanBnXkFtZTcwMjM2NTkxMg@@._V1_.jpg',
    'caption': {'plainText': 'DVD cover of The sons of Eilaboun - Short version'}},
   'releaseDate': {'day': 28,
    'month': 9,
    'year': 2007,
    'country': {'id': 'IL', 'text': 'Israel'}},
   'plot': {'plotText': {'plainText': 'A documentary film that tells the story of the human toll that Plan Dalet claimed on a small Palestinian village in the 1948 war. The story of the massacre, expulsion and return of Eilaboun.'},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'Stealing a Nation'},
   'id': 'tt0803890',
   'primaryImage': {'id': 'rm3879343872',
    'width': 447,
    'height': 640,
    'url': 'https://m.media-amazon.com/images/M/MV5BMDk1YTcwMTUtMDMyYi00ZDFmLTkyMzMtZTY0YzQ2NTk2OWY1XkEyXkFqcGdeQXVyMTgwOTE5NDk@._V1_.jpg',
    'caption': {'plainText': 'Stealing a Nation (2004)'}},
   'releaseDate': {'day': 31,
    'month': 7,
    'year': 2004,
    'country': {'id': 'GB', 'text': 'United Kingdom'}},
   'plot': {'plotText': {'plainText': "This tells a story literally 'hidden from history'. In the 1960s and 70s, British governments, conspiring with American officials, tricked into leaving, then expelled the entire population of the Chagos islands in the Indian Ocean. The aim was to give the principal island of this Crown Colony, Diego Garcia, to the Americans who wanted it as a major military base. Indeed, from Diego Garcia US planes have since bombed Afghanistan and Iraq. The story is told by islanders who were dumped in the slums of Mauritius and in the words of the British officials who left a 'paper trail' of what the International Criminal Court now describes as 'a crime against humanity' ."},
    'language': {'id': 'en-US'}}},
  {'titleText': {'text': 'With God on our Side'},
   'id': 'tt1766204',
   'primaryImage': {'id': 'rm425839360',
    'width': 375,
    'height': 500,
    'url': 'https://m.media-amazon.com/images/M/MV5BMTQ1MzEyMzMzMV5BMl5BanBnXkFtZTgwMjkxMzU0MTE@._V1_.jpg',
    'caption': {'plainText': 'With God on our Side (2010)'}},
   'releaseDate': {'day': 8,
    'month': 4,
    'year': 2010,
    'country': {'id': 'US', 'text': 'United States'}},

In [5]:
data = pd.DataFrame(req.json())

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   movies  40 non-null     object
dtypes: object(1)
memory usage: 448.0+ bytes

In [7]:
data.head()

                                              movies
0  {'titleText': {'text': 'Curfew'}, 'id': 'tt010...
1  {'titleText': {'text': 'Hikayatul jawahiri tha...
2  {'titleText': {'text': 'Giraffada'}, 'id': 'tt...
3  {'titleText': {'text': 'Gaza mon amour'}, 'id'...
4  {'titleText': {'text': 'Farha'}, 'id': 'tt1155...

In [9]:
data['movies']

0     {'titleText': {'text': 'Curfew'}, 'id': 'tt010...
1     {'titleText': {'text': 'Hikayatul jawahiri tha...
2     {'titleText': {'text': 'Giraffada'}, 'id': 'tt...
3     {'titleText': {'text': 'Gaza mon amour'}, 'id'...
4     {'titleText': {'text': 'Farha'}, 'id': 'tt1155...
5     {'titleText': {'text': 'Eyes of a Thief'}, 'id...
6     {'titleText': {'text': 'Habibi Rasak Kharban'}...
7     {'titleText': {'text': 'Falastine Stereo'}, 'i...
8     {'titleText': {'text': 'Chronicle of a Disappe...
9     {'titleText': {'text': 'Laila's Birthday'}, 'i...
10    {'titleText': {'text': 'Lemon Tree'}, 'id': 't...
11    {'titleText': {'text': 'Degrade'}, 'id': 'tt44...
12    {'titleText': {'text': 'Bethlehem'}, 'id': 'tt...
13    {'titleText': {'text': 'Bonboné'}, 'id': 'tt70...
14    {'titleText': {'text': 'Between Heaven and Ear...
15    {'titleText': {'text': 'In Between'}, 'id': 't...
16    {'titleText': {'text': 'Bab el shams'}, 'id': ...
17    {'titleText': {'text': 'Al-mor wa al rumman'},...
18    {'titleText': {'text': 'The Present'}, 'id': '...
19    {'titleText': {'text': 'Love, Theft and Other ...
20    {'titleText': {'text': 'Al-Nakba'}, 'id': 'tt3...
21    {'titleText': {'text': '1948 Palestinian Exodu...
22    {'titleText': {'text': 'The Sons of Eilaboun'}...
23    {'titleText': {'text': 'Stealing a Nation'}, '...
24    {'titleText': {'text': 'With God on our Side'}...
25    {'titleText': {'text': 'Tears of Gaza'}, 'id':...
26    {'titleText': {'text': 'Occupation 101'}, 'id'...
27    {'titleText': {'text': 'Life in Occupied Pales...
28    {'titleText': {'text': 'Gaza Fights for Freedo...
29    {'titleText': {'text': 'Killing Gaza'}, 'id': ...
30    {'titleText': {'text': 'The Oslo Diaries'}, 'i...
31    {'titleText': {'text': 'Born in Gaza'}, 'id': ...
32    {'titleText': {'text': 'Eyes of a Thief'}, 'id...
33    {'titleText': {'text': 'Ghost Hunting'}, 'id':...
34    {'titleText': {'text': 'Hikayatul jawahiri tha...
35    {'titleText': {'text': 'Promises'}, 'id': 'tt0...
36    {'titleText': {'text': 'Gaza mon amour'}, 'id'...
37    {'titleText': {'text': 'Ambulance'}, 'id': 'tt...
38    {'titleText': {'text': 'To See If I'm Smiling'...
39    {'titleText': {'text': 'The Settlers'}, 'id': ...
Name: movies, dtype: object

In [81]:
data1 = pd.DataFrame(req.json()['movies'])

In [82]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   titleText     40 non-null     object
 1   id            40 non-null     object
 2   primaryImage  40 non-null     object
 3   releaseDate   40 non-null     object
 4   plot          40 non-null     object
dtypes: object(5)
memory usage: 1.7+ KB

In [83]:
data1.head()

,titleText,id,primaryImage,releaseDate,plot
0,{'text': 'Curfew'},tt0109996,"{'id': 'rm777481472', 'width': 315, 'height': ...","{'day': 5, 'month': 12, 'year': 1994, 'country...",{'plotText': {'plainText': '24 hours of family...
1,{'text': 'Hikayatul jawahiri thalath'},tt0111354,"{'id': 'rm4037123328', 'width': 284, 'height':...","{'day': 6, 'month': 12, 'year': 1995, 'country...",{'plotText': {'plainText': 'A Palestinian boy ...
2,{'text': 'Giraffada'},tt3132086,"{'id': 'rm2021999616', 'width': 950, 'height':...","{'day': 23, 'month': 4, 'year': 2014, 'country...",{'plotText': {'plainText': 'A male giraffe die...
3,{'text': 'Gaza mon amour'},tt11692148,"{'id': 'rm2123225857', 'width': 1080, 'height'...","{'day': 5, 'month': 11, 'year': 2021, 'country...","{'plotText': {'plainText': 'Gaza, today. Sixty..."
4,{'text': 'Farha'},tt11555492,"{'id': 'rm2816411393', 'width': 4000, 'height'...","{'day': 1, 'month': 12, 'year': 2022, 'country...",{'plotText': {'plainText': 'A 14-year-old girl...

In [15]:
print("Column names:", data.columns)
print()

Column names: Index(['movies'], dtype='object')

In [17]:
for column_name in data.columns:
    column_data = data[column_name]
    print(f"{column_name}:")
    print(column_data)
    print()

movies:
0     {'titleText': {'text': 'Curfew'}, 'id': 'tt010...
1     {'titleText': {'text': 'Hikayatul jawahiri tha...
2     {'titleText': {'text': 'Giraffada'}, 'id': 'tt...
3     {'titleText': {'text': 'Gaza mon amour'}, 'id'...
4     {'titleText': {'text': 'Farha'}, 'id': 'tt1155...
5     {'titleText': {'text': 'Eyes of a Thief'}, 'id...
6     {'titleText': {'text': 'Habibi Rasak Kharban'}...
7     {'titleText': {'text': 'Falastine Stereo'}, 'i...
8     {'titleText': {'text': 'Chronicle of a Disappe...
9     {'titleText': {'text': 'Laila's Birthday'}, 'i...
10    {'titleText': {'text': 'Lemon Tree'}, 'id': 't...
11    {'titleText': {'text': 'Degrade'}, 'id': 'tt44...
12    {'titleText': {'text': 'Bethlehem'}, 'id': 'tt...
13    {'titleText': {'text': 'Bonboné'}, 'id': 'tt70...
14    {'titleText': {'text': 'Between Heaven and Ear...
15    {'titleText': {'text': 'In Between'}, 'id': 't...
16    {'titleText': {'text': 'Bab el shams'}, 'id': ...
17    {'titleText': {'text': 'Al-mor wa al rumman'},...
18    {'titleText': {'text': 'The Present'}, 'id': '...
19    {'titleText': {'text': 'Love, Theft and Other ...
20    {'titleText': {'text': 'Al-Nakba'}, 'id': 'tt3...
21    {'titleText': {'text': '1948 Palestinian Exodu...
22    {'titleText': {'text': 'The Sons of Eilaboun'}...
23    {'titleText': {'text': 'Stealing a Nation'}, '...
24    {'titleText': {'text': 'With God on our Side'}...
25    {'titleText': {'text': 'Tears of Gaza'}, 'id':...
26    {'titleText': {'text': 'Occupation 101'}, 'id'...
27    {'titleText': {'text': 'Life in Occupied Pales...
28    {'titleText': {'text': 'Gaza Fights for Freedo...
29    {'titleText': {'text': 'Killing Gaza'}, 'id': ...
30    {'titleText': {'text': 'The Oslo Diaries'}, 'i...
31    {'titleText': {'text': 'Born in Gaza'}, 'id': ...
32    {'titleText': {'text': 'Eyes of a Thief'}, 'id...
33    {'titleText': {'text': 'Ghost Hunting'}, 'id':...
34    {'titleText': {'text': 'Hikayatul jawahiri tha...
35    {'titleText': {'text': 'Promises'}, 'id': 'tt0...
36    {'titleText': {'text': 'Gaza mon amour'}, 'id'...
37    {'titleText': {'text': 'Ambulance'}, 'id': 'tt...
38    {'titleText': {'text': 'To See If I'm Smiling'...
39    {'titleText': {'text': 'The Settlers'}, 'id': ...
Name: movies, dtype: object

In [18]:
import numpy as np
import pandas as pd
import requests

In [19]:
url = "https://raw.githubusercontent.com/Data-for-Palestine/Palestinian-Movies-JSON-Dataset/main/palestinian_movies.json"

In [20]:
new_req = requests.get(url)

In [42]:
new_data = pd.DataFrame(new_req.json()['movies'])

In [43]:
new_data

,titleText,id,primaryImage,releaseDate,plot
0,{'text': 'Curfew'},tt0109996,"{'id': 'rm777481472', 'width': 315, 'height': ...","{'day': 5, 'month': 12, 'year': 1994, 'country...",{'plotText': {'plainText': '24 hours of family...
1,{'text': 'Hikayatul jawahiri thalath'},tt0111354,"{'id': 'rm4037123328', 'width': 284, 'height':...","{'day': 6, 'month': 12, 'year': 1995, 'country...",{'plotText': {'plainText': 'A Palestinian boy ...
2,{'text': 'Giraffada'},tt3132086,"{'id': 'rm2021999616', 'width': 950, 'height':...","{'day': 23, 'month': 4, 'year': 2014, 'country...",{'plotText': {'plainText': 'A male giraffe die...
3,{'text': 'Gaza mon amour'},tt11692148,"{'id': 'rm2123225857', 'width': 1080, 'height'...","{'day': 5, 'month': 11, 'year': 2021, 'country...","{'plotText': {'plainText': 'Gaza, today. Sixty..."
4,{'text': 'Farha'},tt11555492,"{'id': 'rm2816411393', 'width': 4000, 'height'...","{'day': 1, 'month': 12, 'year': 2022, 'country...",{'plotText': {'plainText': 'A 14-year-old girl...
5,{'text': 'Eyes of a Thief'},tt2993406,"{'id': 'rm22085376', 'width': 814, 'height': 1...","{'day': 1, 'month': 10, 'year': 2014, 'country...",{'plotText': {'plainText': 'A father with a da...
6,{'text': 'Habibi Rasak Kharban'},tt1670646,"{'id': 'rm1752743424', 'width': 3995, 'height'...","{'day': 15, 'month': 5, 'year': 2012, 'country...",{'plotText': {'plainText': ''Habibi Rasak Khar...
7,{'text': 'Falastine Stereo'},tt3121066,"{'id': 'rm2102016000', 'width': 630, 'height':...","{'day': 2, 'month': 6, 'year': 2014, 'country'...",{'plotText': {'plainText': 'Two Palestinian br...
8,{'text': 'Chronicle of a Disappearance'},tt0115895,"{'id': 'rm2871237888', 'width': 344, 'height':...","{'day': None, 'month': None, 'year': 1996, 'co...",{'plotText': {'plainText': 'A Palestinian expa...
9,{'text': 'Laila's Birthday'},tt1281951,"{'id': 'rm3684775681', 'width': 560, 'height':...","{'day': 9, 'month': 4, 'year': 2009, 'country'...",{'plotText': {'plainText': 'Abu Laila used to ...
10,{'text': 'Lemon Tree'},tt1172963,"{'id': 'rm3732179712', 'width': 260, 'height':...","{'day': 27, 'month': 3, 'year': 2008, 'country...",{'plotText': {'plainText': 'The story of a Pal...
11,{'text': 'Degrade'},tt4429074,"{'id': 'rm1215045120', 'width': 736, 'height':...","{'day': 27, 'month': 4, 'year': 2016, 'country...","{'plotText': {'plainText': 'In Gaza, two haird..."
12,{'text': 'Bethlehem'},tt2915160,"{'id': 'rm1833487360', 'width': 4015, 'height'...","{'day': 26, 'month': 9, 'year': 2013, 'country...",{'plotText': {'plainText': 'Tells the story of...
13,{'text': 'Bonboné'},tt7083868,"{'id': 'rm62413312', 'width': 8100, 'height': ...","{'day': 4, 'month': 10, 'year': 2017, 'country...",{'plotText': {'plainText': 'A Palestinian coup...
14,{'text': 'Between Heaven and Earth'},tt10111746,"{'id': 'rm232360193', 'width': 1080, 'height':...","{'day': 2, 'month': 12, 'year': 2020, 'country...",{'plotText': {'plainText': 'Two married young ...
15,{'text': 'In Between'},tt5974388,"{'id': 'rm3107544832', 'width': 1611, 'height'...","{'day': 5, 'month': 1, 'year': 2017, 'country'...",{'plotText': {'plainText': 'Three Palestinian ...
16,{'text': 'Bab el shams'},tt0406551,"{'id': 'rm3200061184', 'width': 350, 'height':...","{'day': 19, 'month': 1, 'year': 2005, 'country...",{'plotText': {'plainText': 'In the beginning w...
17,{'text': 'Al-mor wa al rumman'},tt1320282,"{'id': 'rm850923776', 'width': 517, 'height': ...","{'day': None, 'month': 2, 'year': 2009, 'count...",{'plotText': {'plainText': 'A free spirited Pa...
18,{'text': 'The Present'},tt11474480,"{'id': 'rm92910337', 'width': 2305, 'height': ...","{'day': 18, 'month': 3, 'year': 2021, 'country...",{'plotText': {'plainText': 'On his wedding ann...
19,"{'text': 'Love, Theft and Other Entanglements'}",tt4253322,"{'id': 'rm1309341184', 'width': 467, 'height':...","{'day': 26, 'month': 5, 'year': 2016, 'country...",{'plotText': {'plainText': 'A Palestinian car ...
20,{'text': 'Al-Nakba'},tt3850118,"{'id': 'rm261240833', 'width': 1114, 'height':...","{'day': None, 'month': None, 'year': 2008, 'co...",{'plotText': {'plainText': 'The ethnic cleansi...
21,{'text': '1948 Palestinian Exodus'},tt0163518,"{'id': 'rm2382833664', 'width': 229, 'height':...","{'day': None, 'month': None, 'year': 1997, 'co...",{'plotText': {'plainText': 'The film presents ...
22,{'text': 'The Sons of Eilaboun'},tt1249418,"{'id': 'rm1201834496', 'width': 300, 'height':...","{'day': 28, 'month': 9, 'year': 2007, 'country...",{'plotText': {'plainText': 'A documentary film...
23,{'text': 'Stealing a Nation'},tt0803890,"{'id': 'rm3879343872', 'width': 447, 'height':...","{'day': 31, 'month': 7, 'year': 2004, 'country...",{'plotText': {'plainText': 'This tells a story...
24,{'text': 'With God on our Side'},tt1766204,"{'id': 'rm425839360', 'width': 375, 'height': ...","{'day': 8, 'month': 4, 'year': 2010, 'country'...",{'plotText': {'plainText': 'The minute ur past...
25,{'text': 'Tears of Gaza'},tt1699705,"{'id': 'rm1780282624', 'width': 375, 'height':...","{'day': 21, 'month': 12, 'year': 2012, 'countr...","{'plotText': {'plainText': 'In a rough style, ..."
26,{'text': 'Occupation 101'},tt0807956,"{'id': 'rm3486488320', 'width': 548, 'height':...","{'day': 15, 'month': 5, 'year': 2007, 'country...",{'plotText': {'plainText': 'A thought-provokin...
27,{'text': 'Life in Occupied Palestine: Eyewitne...,tt16749956,"{'id': 'rm2157044225', 'width': 650, 'height':...","{'day': None, 'month': None, 'year': 1997, 'co...","{'plotText': {'plainText': 'Anna Baltzer, the ..."
28,{'text': 'Gaza Fights for Freedom'},tt10825504,"{'id': 'rm139035905', 'width': 544, 'height': ...","{'day': 20, 'month': 6, 'year': 2019, 'country...",{'plotText': {'plainText': 'Filmed during the ...
29,{'text': 'Killing Gaza'},tt8438864,"{'id': 'rm1822737921', 'width': 707, 'height':...","{'day': 13, 'month': 5, 'year': 2018, 'country...","{'plotText': {'plainText': 'In Killing Gaza, i..."
30,{'text': 'The Oslo Diaries'},tt7689940,"{'id': 'rm724587264', 'width': 1012, 'height':...","{'day': None, 'month': 1, 'year': 2018, 'count...",{'plotText': {'plainText': 'A group of Israeli...
31,{'text': 'Born in Gaza'},tt4205416,"{'id': 'rm2398001665', 'width': 426, 'height':...","{'day': 16, 'month': 5, 'year': 2019, 'country...",{'plotText': {'plainText': 'Filmed shortly aft...
32,{'text': 'Eyes of a Thief'},tt2993406,"{'id': 'rm22085376', 'width': 814, 'height': 1...","{'day': 1, 'month': 10, 'year': 2014, 'country...",{'plotText': {'plainText': 'A father with a da...
33,{'text': 'Ghost Hunting'},tt6568868,"{'id': 'rm2696885760', 'width': 800, 'height':...","{'day': 13, 'month': 10, 'year': 2021, 'countr...",{'plotText': {'plainText': 'Some Palestinians ...
34,{'text': 'Hikayatul jawahiri thalath'},tt0111354,"{'id': 'rm4037123328', 'width': 284, 'height':...","{'day': 6, 'month': 12, 'year': 1995, 'country...",{'plotText': {'plainText': 'A Palestinian boy ...
35,{'text': 'Promises'},tt0282864,"{'id': 'rm2189663488', 'width': 352, 'height':...","{'day': 20, 'month': 12, 'year': 2001, 'countr...",{'plotText': {'plainText': 'Several Jewish and...
36,{'text': 'Gaza mon amour'},tt11692148,"{'id': 'rm2123225857', 'width': 1080, 'height'...","{'day': 5, 'month': 11, 'year': 2021, 'country...","{'plotText': {'plainText': 'Gaza, today. Sixty..."
37,{'text': 'Ambulance'},tt6141880,"{'id': 'rm448135936', 'width': 1786, 'height':...","{'day': 7, 'month': 6, 'year': 2017, 'country'...",{'plotText': {'plainText': 'During the summer ...
38,{'text': 'To See If I'm Smiling'},tt1112866,"{'id': 'rm3591978752', 'width': 245, 'height':...","{'day': None, 'month': None, 'year': 2007, 'co...",{'plotText': {'plainText': 'Six Israeli soldie...
39,{'text': 'The Settlers'},tt5278914,"{'id': 'rm556085760', 'width': 2013, 'height':...","{'day': 16, 'month': 6, 'year': 2016, 'country...",{'plotText': {'plainText': 'An intimate look a...

In [51]:
import pandas as pd
import requests

In [52]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [53]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [54]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,141.956,8.700,26385
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,167.366,8.693,20011
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,119.775,8.577,12081
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,94.075,8.567,15489
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,80.012,8.545,8334

In [55]:
df = pd.DataFrame()

In [56]:
df

Empty DataFrame
Columns: []
Index: []

In [59]:
import pandas as pd
import requests

# Initialize an empty list to store DataFrames
dfs = []

# Loop through pages
for i in range(1, 429):
    # Make API request
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))

    # Extract relevant data from response and create temporary DataFrame
    temp_df = pd.DataFrame(response.json()['results'], columns=['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count'])

    # Append to list
    dfs.append(temp_df)

# Concatenate all DataFrames in the list
df = pd.concat(dfs, ignore_index=True)

# Print the first few rows of the DataFrame to verify
print(df.head())

    id                     title  \
0  278  The Shawshank Redemption
1  238             The Godfather
2  240     The Godfather Part II
3  424          Schindler's List
4  389              12 Angry Men

                                            overview release_date  popularity  \
0  Imprisoned in the 1940s for the double murder ...   1994-09-23     141.956
1  Spanning the years 1945 to 1955, a chronicle o...   1972-03-14     167.366
2  In the continuing saga of the Corleone crime f...   1974-12-20     119.775
3  The true story of how businessman Oskar Schind...   1993-12-15      94.075
4  The defense and the prosecution have rested an...   1957-04-10      80.012

   vote_average  vote_count
0         8.700       26385
1         8.693       20011
2         8.577       12081
3         8.567       15489
4         8.545        8334

In [60]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,141.956,8.700,26385
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,167.366,8.693,20011
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,119.775,8.577,12081
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,94.075,8.567,15489
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,80.012,8.545,8334